### ISSUE TITLE
statically build iascar

### ISSUE THREAD

**Issue by mahi045** [drwadu/iascar#5]
Hi,
Do you have any command to statically build iascar? I have tried with the following one:
```
RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
```

Unfortunately, I was not able to build with that.

Thanks in advance.

**Comment by drwadu** [comment]
hi, I  suppose that the proposed command is (in general) fine. 

Even though, you haven't provided the information on the error(s) you received,  from my own experience, I assume that statically linking to clingo (due to the [clingo-rs](https://github.com/potassco/clingo-rs) dependency) is involved in your issue. I have not managed to resolve this issue yet, sorry.  

However, in the [branch](https://github.com/drwadu/iascar/tree/5-statically-build-iascar) related to this issue I came up with a workaround, which enables statically building parts of iascar. The resulting iascar binary can be used for counting on NNFs or CCGs only, that is, no compression (-com) and no enumeration (-enum) functionalities are available, as both depend on clingo. 

I hope this helps smh.

**Comment by mahi045** [comment]
Hi @drwadu 
Thank you. It was really helpful.
